---
- name: Copy Files from Minio to Windows
  hosts: 10.10.5.184
  gather_facts: no

  tasks:
    - name: Download file from Minio
      get_url:
        url: "https://10.10.5.76:9001/browser/security/U1FMaXRlLw=="
        dest: "/mnt/data/security/SQLite"
        headers:
          Authorization: "Bearer {{ minio_access_key }}:{{ minio_secret_key }}"
      delegate_to: 10.10.5.76

 

    - name: Copy file to Windows
      win_copy:
        src: "/security/SQLite"
        dest: "C:"/mnt/data/security/SQLite"
      become: yes
      become_user: Administrator
